import {
    Button,
    VerticalBox,
    HorizontalBox,
    CheckBox,
    SpinBox,
} from "std-widgets.slint";

export struct CellData {
    x_pos: int,
    y_pos: int,
    has_peg: bool,
}

export component AppWindow inherits Window {
    in-out property <int> board_size;

    property <length> cell_size: 400px / root.board_size;    

    in-out property <string> hovered_cell: "";
    in-out property <string> selected_cell: "";
    in-out property <[CellData]> cells;

    callback peg_cell_clicked(x_pos: int, y_pos: int);
    callback peg_cell_hovered(x_pos: int, y_pos: int);
    callback new_game_clicked();
    callback board_size_changed(int);

    VerticalBox {
        Text {
            text: "Hovered: \{root.hovered_cell}";
        }

        Text {
            text: "Selected Start: \{root.selected_cell}";
        }

        Rectangle {
            width: root.cell_size * root.board_size;
            height: root.cell_size * root.board_size;

            for cell in root.cells: Rectangle {
                width: root.cell_size;
                height: root.cell_size;
                x: cell.x_pos * root.cell_size;
                y: cell.y_pos * root.cell_size;
                border-width: 2px;
                border-color: white;

                background: touch.has-hover ? #555 : #333;

                touch := TouchArea {
                    clicked => {
                        root.peg_cell_clicked(cell.x_pos, cell.y_pos);
                        root.selected_cell = "(\{cell.x_pos}, \{cell.y_pos})";
                    }
                    pointer-event(event) => {
                        if self.has-hover {
                            root.peg_cell_hovered(cell.x_pos, cell.y_pos);
                            root.hovered_cell = "(\{cell.x_pos}, \{cell.y_pos})";
                        }
                    }
                }

                // Peg circle
                Rectangle {
                    width: 10px;
                    height: 10px;
                    border-radius: self.width / 2;
                    background: red;
                    visible: cell.has_peg;
                    x: parent.width / 2 - self.width / 2;
                    y: parent.height / 2 - self.height / 2;
                }
            }
        }

        Button {
            text: "New Game";
            clicked => {
                root.new_game_clicked();
            }
        }

        HorizontalBox {
            Text { text: "Board Size:"; }

            SpinBox {
                minimum: 5;
                maximum: 15;
                value: root.board_size;

                edited(value) => {
                    root.board_size = self.value;
                    root.board_size_changed(self.value);
                }
            }
        }
    }
}