import {
    Button,
    VerticalBox,
    HorizontalBox,
    CheckBox,
} from "std-widgets.slint";

export component PegCell inherits Rectangle {
    in property <int> x_pos;
    in property <int> y_pos;
    in-out property <string> hovered_cell;
    in-out property <string> selected_cell;
    in-out property <string> name;
    in property <bool> has_peg;
    
    callback clicked(x_pos: int, y_pos: int);
    callback hovered(x_pos: int, y_pos: int);

    background: area.has-hover ? #555 : #333;
    
    area := TouchArea {
        clicked => {
            root.clicked(root.x_pos, root.y_pos);
        }

        pointer-event(event) => {
            if area.has-hover {
                root.hovered(root.x_pos, root.y_pos);
            }
        }
    }

    // Draw the peg as a circle if has_peg is true
    Rectangle {
        width: 10px;
        height: 10px;
        border-radius: self.width / 2;
        background: red;
        visible: root.has_peg;
        x: parent.width / 2 - self.width / 2;
        y: parent.height / 2 - self.height / 2;
    }
}

export component AppWindow inherits Window {
    in-out property <int> counter: 0;
    in-out property <string> hovered_cell: "";
    in-out property <string> selected_cell: "";
    in-out property <bool> mode1;
    in-out property <bool> mode2;
    in-out property <bool> mode3;

    callback peg_cell_clicked(x_pos: int, y_pos: int);
    callback peg_cell_hovered(x_pos: int, y_pos: int);

    callback request-increase-value();
    callback request-decrease-value();
    VerticalBox {
        Text {
            text: "Hovered: \{root.hovered_cell}";
        }

        Text {
            text: "Selected Start: \{root.selected_cell}";
        }

        VerticalBox {
            width: 400px;
            height: 400px;
            GridLayout {
        // Row 1
        Rectangle { }

                Rectangle { }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 0;
                    name: "cell_2_0";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 0;
                    name: "cell_3_0";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 0;
                    name: "cell_4_0";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                Rectangle { }

                Rectangle { }

        // Row 2
        Rectangle {
                    row: 1;
                }

                Rectangle { }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 1;
                    name: "cell_2_1";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 1;
                    name: "cell_3_1";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 1;
                    name: "cell_4_1";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                Rectangle { }

                Rectangle { }

        // Row 3
        PegCell {
                    border-width: 2px;
                    border-color: white;
                    row: 2;
                    x_pos: 0;
                    y_pos: 2;
                    name: "cell_0_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 1;
                    y_pos: 2;
                    name: "cell_1_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 2;
                    name: "cell_2_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 2;
                    name: "cell_3_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 2;
                    name: "cell_4_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 5;
                    y_pos: 2;
                    name: "cell_5_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 6;
                    y_pos: 2;
                    name: "cell_6_2";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

        // Row 4
        PegCell {
                    border-width: 2px;
                    border-color: white;
                    row: 3;
                    x_pos: 0;
                    y_pos: 3;
                    name: "cell_0_3";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 1;
                    y_pos: 3;
                    name: "cell_1_3";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 3;
                    name: "cell_2_3";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 3;
                    name: "cell_3_3";
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 3;
                    name: "cell_4_3";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 5;
                    y_pos: 3;
                    name: "cell_5_3";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 6;
                    y_pos: 3;
                    name: "cell_6_3";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

        // Row 5
        PegCell {
                    border-width: 2px;
                    border-color: white;
                    row: 4;
                    x_pos: 0;
                    y_pos: 4;
                    name: "cell_0_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 1;
                    y_pos: 4;
                    name: "cell_1_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 4;
                    name: "cell_2_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 4;
                    name: "cell_3_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 4;
                    name: "cell_4_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 5;
                    y_pos: 4;
                    name: "cell_5_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 6;
                    y_pos: 4;
                    name: "cell_6_4";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

        // Row 6
        Rectangle {
                    row: 5;
                }

                Rectangle { }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 5;
                    name: "cell_2_5";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 5;
                    name: "cell_3_5";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 5;
                    name: "cell_4_5";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                Rectangle { }

                Rectangle { }

        // Row 7
        Rectangle {
                    row: 6;
                }

                Rectangle { }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 2;
                    y_pos: 6;
                    name: "cell_2_6";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 3;
                    y_pos: 6;
                    name: "cell_3_6";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                PegCell {
                    border-width: 2px;
                    border-color: white;
                    x_pos: 4;
                    y_pos: 6;
                    name: "cell_4_6";
                    has_peg: true;
                    clicked(x_pos, y_pos) => {
                        root.peg_cell_clicked(x-pos, y-pos);
                        root.selected_cell = "(\{x-pos}, \{y-pos})";
                    }
                    hovered(x_pos, y_pos) => {
                        root.peg_cell_hovered(x-pos, y-pos);
                        root.hovered_cell = "(\{x-pos}, \{y-pos})";
                    }
                }

                Rectangle { }

                Rectangle { }
            }
        }
    }
}
